# Generated by Django 5.2.10 on 2026-01-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='frequency',
            field=models.CharField(default='once daily', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
