# Generated by Django 5.2.10 on 2026-01-23 20:40

from django.db import migrations
from datetime import date

def seed_data(apps, schema_editor):
    Medication = apps.get_model("medications", "Medication")

    if Medication.objects.filter(patient_id="patient_001").exists():
        return

    Medication.objects.bulk_create([
        # Prenatal Vitamin
        Medication(
            patient_id="patient_001",
            medication_name="Prenatal Vitamin",
            dose="1 tablet",
            frequency="once daily",
            route="oral",
            start_date=date(2025, 12, 15),
            end_date=None,
            source="Outpatient Clinic",
            reason="Prenatal supplementation",
            notes="Patient reports continued use",
        ),

        # Ferrous Sulfate
        Medication(
            patient_id="patient_001",
            medication_name="Ferrous Sulfate",
            dose="325 mg",
            frequency="once daily",
            route="oral",
            start_date=date(2025, 11, 1),
            end_date=date(2025, 12, 1),
            source="Outpatient Clinic",
            reason="Iron deficiency anemia",
            notes="Completed course",
        ),

        # Labetalol – Hospital A (100 mg)
        Medication(
            patient_id="patient_001",
            medication_name="Labetalol",
            dose="100 mg",
            frequency="twice daily",
            route="oral",
            start_date=date(2026, 1, 1),
            end_date=date(2026, 1, 10),
            source="Hospital A",
            reason="Gestational hypertension",
            notes="Initiated during admission",
        ),

        # Labetalol – Hospital B (100 mg)
        Medication(
            patient_id="patient_001",
            medication_name="Labetalol",
            dose="100 mg",
            frequency="twice daily",
            route="oral",
            start_date=date(2026, 1, 1),
            end_date=date(2026, 1, 12),
            source="Hospital B",
            reason="Gestational hypertension",
            notes="Imported from external EHR",
        ),

        # Labetalol – Hospital A (200 mg)
        Medication(
            patient_id="patient_001",
            medication_name="Labetalol",
            dose="200 mg",
            frequency="twice daily",
            route="oral",
            start_date=date(2026, 1, 11),
            end_date=date(2026, 1, 25),
            source="Hospital A",
            reason="Persistent hypertension",
            notes="Dose increased after elevated BP readings",
        ),

        # Aspirin
        Medication(
            patient_id="patient_001",
            medication_name="Aspirin",
            dose="81 mg",
            frequency="once daily",
            route="oral",
            start_date=date(2025, 10, 1),
            end_date=None,
            source="Outpatient Clinic",
            reason="Preeclampsia risk reduction",
            notes="Low-dose aspirin prophylaxis",
        ),

        # Magnesium Sulfate – Hospital A
        Medication(
            patient_id="patient_001",
            medication_name="Magnesium Sulfate",
            dose="2 g/hr",
            frequency="continuous infusion",
            route="IV",
            start_date=date(2026, 1, 5),
            end_date=date(2026, 1, 7),
            source="Hospital A",
            reason="Seizure prophylaxis",
            notes="Administered during labor",
        ),

        # Magnesium Sulfate – Hospital B
        Medication(
            patient_id="patient_001",
            medication_name="Magnesium Sulfate",
            dose="1 g/hr",
            frequency="continuous infusion",
            route="IV",
            start_date=date(2026, 1, 6),
            end_date=date(2026, 1, 8),
            source="Hospital B",
            reason="Seizure prophylaxis",
            notes="Different dosing documented during transfer",
        ),

        # Oxytocin
        Medication(
            patient_id="patient_001",
            medication_name="Oxytocin",
            dose="4 mU/min",
            frequency="continuous infusion",
            route="IV",
            start_date=date(2026, 1, 6),
            end_date=date(2026, 1, 6),
            source="Hospital A",
            reason="Labor induction",
            notes="Used during active labor",
        ),

        # Acetaminophen
        Medication(
            patient_id="patient_001",
            medication_name="Acetaminophen",
            dose="650 mg",
            frequency="every 6 hours",
            route="oral",
            start_date=date(2026, 1, 4),
            end_date=None,
            source="Emergency Department",
            reason="Headache",
            notes="PRN use; end date not documented",
        ),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_medication_frequency_medication_reason'),
    ]

    operations = [migrations.RunPython(seed_data)]
